service: flow-api

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2
  stage: ${opt:stage, 'dev'}
  vpc:
    securityGroupIds:
      - ${ssm:/flow/SECURITY_GROUP_ID}
    subnetIds: ${ssm:/flow/PRIVATE_SUBNET_IDS}
  environment:
    ENVIRONMENT: ${self:provider.stage}
    NODE_ENV: ${self:custom.nodeEnv.${self:provider.stage}}
    # DATABASE_URL: ${ssm:/flow/COGNITO_USER_POOL_NAME} - TODO: Uncomment when FLOW-7 is in place
    DATABASE_URL: postgresql://postgres@localhost:5432/flow

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 3000
  nodeEnv:
    dev: development
    prod: production

functions:
  storeUser:
    handler: src/functions/user.storeHandler
    events:
      - cognitoUserPool:
          pool: ${ssm:/flow/COGNITO_USER_POOL_NAME}
          trigger: PostConfirmation
          existing: true