service: flow-api

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2
  stage: ${opt:stage, 'dev'}
  vpc:
    securityGroupIds:
      - ${ssm:/flow/SECURITY_GROUP_ID}
    subnetIds: ${ssm:/flow/PRIVATE_SUBNET_IDS}
  environment:
    ENVIRONMENT: ${self:provider.stage}
    NODE_ENV: ${self:custom.nodeEnv.${self:provider.stage}}
    # DATABASE_URL: postgresql://postgres@localhost:5432/flow
    DATABASE_URL: ${ssm:/flow/rds/DB_URL}
    FLOW_APP_URL: ${self:custom.flowAppUrl.${self:provider.stage}}
    STRIPE_SECRET_KEY: ${ssm:/flow/stripe/SECRET_KEY}
  
package:
  excludeDevDependencies: true
  individually: true
  patterns:
    - "!tests/**"

custom:
  flowAppUrl:
    # dev: http://localhost:5173
    dev: https://flow-dev.nsar-tech.co.uk
    prod: https://flow.nsar-tech.co.uk
  serverless-offline:
    host: 0.0.0.0
    httpPort: 3000
  nodeEnv:
    dev: development
    prod: production
  domain: flow-api${self:custom.stageDomainPrefix.${self:provider.stage}}.nsar-tech.co.uk
  stageDomainPrefix:
    dev: "-dev"
    prod: ""
  customDomain:
    rest:
      domainName: ${self:custom.domain}
      createRoute53Record: false # managed in root account
      endpointType: "regional"
      certificateArn: ${ssm:/nsar-tech/CERTIFICATE_ARN}
      autoDomain: true
      autoDomainWaitFor: 120

functions:
  # Flow Cognito User Pool
  storeUser:
    handler: src/functions/user.storeHandler
    events:
      - cognitoUserPool:
          pool: ${ssm:/flow/COGNITO_USER_POOL_NAME}
          trigger: PostConfirmation
          existing: true
  
  # Admin Dashboard
  createOrganisation:
    handler: src/functions/organisation.createHandler
    events:
      - http:
          path: /organisations
          method: post
          cors: true
  
  # Stripe
  stripeWebhook:
    handler: src/functions/stripe.webhookHandler
    events:
      - http:
          path: /stripe/webhook
          method: post
          cors: true
  stripeCreateSession:
    handler: src/functions/stripe.createSessionHandler
    events:
      - http:
          path: /stripe/session
          method: post
          cors: true
  stripeGetSession:
    handler: src/functions/stripe.getSessionHandler
    events:
      - http:
          path: /stripe/session/{sessionId}
          method: get
          cors: true
