service: flow-api

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-2
  stage: ${opt:stage, 'dev'}
  environment:
    ENVIRONMENT: ${self:provider.stage}
    NODE_ENV: ${self:custom.nodeEnv.${self:provider.stage}}

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 3000
  nodeEnv:
    dev: development
    prod: production

functions:
  storeUser:
    handler: src/functions/user.storeHandler
    events:
      - cognitoUserPool:
          pool: ${ssm:/flow/COGNITO_USER_POOL_NAME}
          trigger: PostConfirmation
          existing: true